"""LLM bias assessment for the BiasBuster CLI.

Uses the v3 two-call architecture for both abstract and full-text papers:
- Abstract: Stage 1 extraction → Stage 2 assessment (see
  ``BaseAnnotator.annotate_abstract_two_call``).
- Full text: section-level Stage 1 extractions → merge → Stage 2 assessment
  (see ``BaseAnnotator.annotate_full_text_two_call``).

Both paths share the same prompts, merge logic, and JSON validation with
the training-data pipeline in ``pipeline.py``. This ensures inference and
training data are generated by identical code paths.
"""

from __future__ import annotations

import asyncio
import logging
from typing import Any

from bmlib.llm import LLMClient

from biasbuster.annotators.bmlib_backend import BmlibAnnotator
from biasbuster.cli.chunking import chunk_jats_article, chunk_plain_text
from biasbuster.cli.settings import CLIConfig
from biasbuster.cli.content import AcquiredContent

logger = logging.getLogger(__name__)

def create_llm_client(config: CLIConfig) -> LLMClient:
    """Create a bmlib LLMClient configured from CLI settings.

    Args:
        config: CLI configuration with provider credentials and endpoints.

    Returns:
        Configured LLMClient instance.
    """
    return LLMClient(
        default_provider=config.provider,
        ollama_host=config.ollama_endpoint,
        anthropic_api_key=config.anthropic_api_key,
        api_key=config.deepseek_api_key or config.anthropic_api_key,
        base_url=config.deepseek_base if config.provider == "deepseek" else None,
    )


def _make_annotator(llm: LLMClient, config: CLIConfig) -> BmlibAnnotator:
    """Build a BmlibAnnotator from a bmlib LLMClient + CLI config.

    Extra chat kwargs pass through provider-specific options. We disable
    Ollama's extended thinking for Ollama providers because extraction is a
    mechanical task that doesn't benefit from reasoning and some models
    exhaust their token budget in <think> blocks before producing JSON.
    """
    extra_kwargs: dict[str, Any] = {}
    if config.provider == "ollama":
        extra_kwargs["think"] = False

    return BmlibAnnotator(
        client=llm,
        model=config.model,
        temperature=config.temperature,
        max_tokens=config.max_tokens,
        extra_chat_kwargs=extra_kwargs,
    )


def analyse(content: AcquiredContent, config: CLIConfig) -> dict[str, Any]:
    """Run bias assessment on acquired content.

    Routes to two-call annotation (abstract or full-text map-reduce) based
    on whether full text is available.

    Args:
        content: Acquired content (abstract, JATS full text, or plain full text).
        config: CLI configuration.

    Returns:
        Parsed assessment dict with 5-domain bias analysis and nested
        ``extraction`` from Stage 1.
    """
    llm = create_llm_client(config)
    annotator = _make_annotator(llm, config)

    if content.has_fulltext:
        return asyncio.run(_analyse_fulltext(annotator, content))
    return asyncio.run(_analyse_abstract(annotator, content))


async def _analyse_abstract(
    annotator: BmlibAnnotator,
    content: AcquiredContent,
) -> dict[str, Any]:
    """Two-call analysis of an abstract via ``annotate_abstract_two_call``."""
    metadata = _build_metadata_dict(content)
    logger.info(
        "Sending abstract to %s for two-call analysis", annotator.model
    )
    async with annotator:
        result = await annotator.annotate_abstract_two_call(
            pmid=content.pmid,
            title=content.title,
            abstract=content.abstract,
            metadata=metadata,
        )
    if result is None:
        raise ValueError(
            "Two-call abstract annotation failed after retries "
            f"(pmid={content.pmid})"
        )
    return result


async def _analyse_fulltext(
    annotator: BmlibAnnotator,
    content: AcquiredContent,
) -> dict[str, Any]:
    """Map-reduce two-call analysis of full-text content.

    Each chunk feeds ``annotate_full_text_two_call``'s per-section Stage 1
    extraction. The partial extractions are merged (see
    ``merge_section_extractions``), then passed to Stage 2 assessment.
    """
    if content.jats_article is not None:
        chunks = chunk_jats_article(
            content.jats_article, jats_xml=content.jats_xml,
        )
        logger.info(
            "Split JATS article into %d section chunks", len(chunks)
        )
    else:
        chunks = chunk_plain_text(content.plain_fulltext)
        logger.info(
            "Split plain text into %d token-window chunks", len(chunks)
        )

    if not chunks:
        logger.warning("No chunks produced, falling back to abstract analysis")
        return await _analyse_abstract(annotator, content)

    sections = [(chunk.section, chunk.text) for chunk in chunks]
    metadata = _build_metadata_dict(content)

    async with annotator:
        result = await annotator.annotate_full_text_two_call(
            pmid=content.pmid,
            title=content.title,
            sections=sections,
            metadata=metadata,
        )
    if result is None:
        raise ValueError(
            "Full-text two-call annotation failed after retries "
            f"(pmid={content.pmid})"
        )
    return result


def _build_metadata_dict(content: AcquiredContent) -> dict[str, Any] | None:
    """Build metadata dict from AcquiredContent for the annotator."""
    meta: dict[str, Any] = {}
    if content.authors:
        meta["authors"] = content.authors
    if content.journal:
        meta["journal"] = content.journal
    return meta if meta else None
